/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const TEA_BLOCK_LEN: number
export const TEA_KEY_LEN: number
export declare function teaDecrypt(value: Buffer, key: Buffer, iter: number): Buffer
export declare function teaEncrypt(value: Buffer, key: Buffer, iter: number): Buffer
